import { NextPage } from "next";
import Page from "../components/Page";
import LandingPageTemplate from "../templates/LandingPage/LandingPageTemplate";

const Index: NextPage = () => {
  return (
    <Page
      title="b4483c6a-9e53-4f2a-94cf-d6374cf1491f"
      description="Generated by Create Next Stack."
    >
      <LandingPageTemplate />
    </Page>
  );
};

export default Index;
